hello first guide
hackersground-kr/GithubWordRelay pull request #84
Opened 2024-05-18 13:15 UTC by ChoiKangM

2024-05-18 13:28 UTC, level120 requested changes

2024-05-18 13:28 UTC, level120 commented on docs/firstguide.md
> +Github 기초/활용 세미나는 현직자분들과 Microsoft 학생 홍보대사인 MLSA가 진행하며, 질좋은 강의를 위해 노력하겠습니다. 또한, 이번 세미나는 해커그라운드, 클라우드 유랑단, 경북대 컴퓨터학부에서 지원해주기에, 행사 중 다양한 커뮤니티를 만나는 계기가 될 것 입니다 :) 노쇼없이 참가해주시길 간곡히 부탁드리며, 혹시 불가피한 사정이 생겨 불
```suggestion
GitHub 기초/활용 세미나는 현직자분들과 Microsoft 학생 홍보대사인 MLSA가 진행하며, 질좋은 강의를 위해 노력하겠습니다. 또한, 이번 세미나는 해커그라운드, 클라우드 유랑단, 경북대 컴퓨터학부에서 지원해주기에, 행사 중 다양한 커뮤니티를 만나는 계기가 될 것 입니다 :) 노쇼없이 참가해주시길 간곡히 부탁드리며, 혹시 불가피한 사정이 생겨 불참할 경우 꼭 알려주세요! (문의 : jyeon4580@knu.ac.kr)
```

2024-05-18 13:28 UTC, level120 commented on docs/firstguide.md
> +
네트워킹 시간이 처음 접하신 분들은 어떤 의미인지 잘 모르실텐데요, 이런 설명을 추가해보는 것은 어떨까요?

```suggestion
* 일시 : 5월 25일 토요일 오후 18:30~21:00
  * 네트워킹 시간 : 17:45 ~ 강의 시작 전까지(필참 X)
* 장소 : 경북대학교 어딘가 (폼 제출 시 작성해주신 메일로 추후 공지합니다)
* 인원 : 각 강의 당 40명 - 총 80명 (신청이 초과할 경우 참가비 입금 순)

본 행사는 해커그라운드, 클라우드 유랑단에서 지원 및 진행하고 경북대 컴퓨터학부에서 지원합니다.  

* 네크워킹 시간이란, 본 행사를 시작하기에 앞서 같은 관심사를 가진 사람들이 모여 자유롭게 이야기를 할 수 있는 시간입니다. 이 시간에는 행사에 대한 학습, 동아리 활동, 운영에 대한 내용은 물론 실무에서 사용하는 기술이나 그 외 다른 궁금한 점도 얼마든지 자유롭게 이야기할 수 있습니다.
```

2024-05-18 13:28 UTC, level120 commented on docs/firstguide.md
CoC 링크도 하나 추가 부탁드려요!

2024-05-19 02:53 UTC, ChoiKangM commented on docs/firstguide.md
[해커그라운드 COC](https://github.com/hackersground-kr/.github/blob/main/CODE_OF_CONDUCT.md) 요게 있네요 이거루 추가해둘께요!

2024-05-19 03:04 UTC, level120 requested changes

2024-05-19 03:04 UTC, level120 commented on docs/firstguide.md
> +### ✅ 참가 확정
여기 개행이 필요해 보여요.

```suggestion
* 네크워킹 시간이란, 본 행사를 시작하기에 앞서 같은 관심사를 가진 사람들이 모여 자유롭게 이야기를 할 수 있는 시간입니다. 이 시간에는 행사에 대한 학습, 동아리 활동, 운영에 대한 내용은 물론 실무에서 사용하는 기술이나 그 외 다른 궁금한 점도 얼마든지 자유롭게 이야기할 수 있습니다.

### ✅ 참가 확정
```

2024-05-19 03:04 UTC, level120 commented on docs/firstguide.md
> +* GitHub 기초 :
여기도요.

```suggestion
### 📄 강의자료

* GitHub 기초 :
```

2024-05-23 05:25 UTC, merged